// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk-ocr.djinni

#pragma once

#include <string>
#include <utility>

namespace ge {

/** The input of the OCR engine. */
struct OCREngineInput final {
    /** The path of the image to apply OCR to. */
    std::string imagePath;

    OCREngineInput(std::string imagePath_)
    : imagePath(std::move(imagePath_))
    {}

    OCREngineInput()
    : imagePath()
    {}
};

}  // namespace ge
