// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk-pdf.djinni

#import <Foundation/Foundation.h>


/**
 * Used to preprocess pages of the PDF generation.
 *
 * When you generate a PDF document from images, you may want to apply some preprocessing to each image
 * before inserting them in the document (for instance resizing them, including a watermark, etc.) You can
 * implement your own PDF_image_processor and pass it when generating a PDF document.
 * to achieve this.
 */
@protocol GSKPDFImageProcessor <NSObject>

/**
 * Process the image and return a file path to the
 * updated image. The PDF processor will delete this temporary
 * image afterwards (only if it's different from inputFilePath )
 * @return NULL if there is an error
 *
 */
- (nullable NSString *)process:(nonnull NSString *)inputFilePath;

@end
