// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk-pdf.djinni

#import <Foundation/Foundation.h>

/** A configuration for the PDF generator */
@interface GSKPDFGeneratorConfiguration : NSObject
- (nonnull instancetype)initWithFontPath:(nullable NSString *)fontPath
                          iccProfilePath:(nullable NSString *)iccProfilePath
                                   debug:(BOOL)debug;
+ (nonnull instancetype)PDFGeneratorConfigurationWithFontPath:(nullable NSString *)fontPath
                                               iccProfilePath:(nullable NSString *)iccProfilePath
                                                        debug:(BOOL)debug;

@property (nonatomic, readonly, nullable) NSString * fontPath;

/**
 * An ICC profile file that will be configured on the
 * PDF file. This is needed to have PDF/A compliance.
 * It's a RGB profile so that it supports any RGB or Grayscale
 * image.
 */
@property (nonatomic, readonly, nullable) NSString * iccProfilePath;

/**
 * If true, OCR'ed text will visible on the PDF.
 * Defaults to false
 */
@property (nonatomic, readonly) BOOL debug;

@end
