// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk-pdf.djinni

#import <Foundation/Foundation.h>

/**
 * Physical size of a PDF page in inches.
 * If the aspect ratio doesn't match the aspect ratio of the page in pixels,
 * margins will be added on both sides of the page image.
 * If 0 is provided for the width or height, it is computed to match the aspect ratio
 * of the image. Eg, for a receipt, we usually use width = 3.54f and height = 0.
 */
@interface GSKPDFSize : NSObject
- (nonnull instancetype)initWithWidth:(double)width
                               height:(double)height;
+ (nonnull instancetype)PDFSizeWithWidth:(double)width
                                  height:(double)height;

@property (nonatomic, readonly) double width;

@property (nonatomic, readonly) double height;

@end
