// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk-core.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, GSKTextLayoutToTextConverterStatus)
{
    GSKTextLayoutToTextConverterStatusSuccess,
    GSKTextLayoutToTextConverterStatusInvalidHOCRError,
    GSKTextLayoutToTextConverterStatusInternalError,
};
