// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk-core.djinni

#import "GSKTextLayoutToTextConverterStatus.h"
#import <Foundation/Foundation.h>

@interface GSKTextLayoutToTextConverterResult : NSObject
- (nonnull instancetype)initWithStatus:(GSKTextLayoutToTextConverterStatus)status
                                  text:(nonnull NSString *)text
                 averageWordConfidence:(int32_t)averageWordConfidence
                             wordCount:(int32_t)wordCount;
+ (nonnull instancetype)textLayoutToTextConverterResultWithStatus:(GSKTextLayoutToTextConverterStatus)status
                                                             text:(nonnull NSString *)text
                                            averageWordConfidence:(int32_t)averageWordConfidence
                                                        wordCount:(int32_t)wordCount;

/** The status of the conversion. If failure, the other values in the result must not be used. */
@property (nonatomic, readonly) GSKTextLayoutToTextConverterStatus status;

/** The text reconstructed from the text layout. */
@property (nonatomic, readonly, nonnull) NSString * text;

/**
 * The average word confidence of the recognized text.
 * A value between 0 and 100
 */
@property (nonatomic, readonly) int32_t averageWordConfidence;

/**
 * The number of words in the recognized text.
 * This is the number of words on which the average word confidence has been computed.
 */
@property (nonatomic, readonly) int32_t wordCount;

@end
