// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk-core.djinni

#import <Foundation/Foundation.h>

/**
 * The text layout of a scan
 *
 * This is part of the output of the OCR recognition, but can also be part of the input of the PDF generation.
 */
@interface GSKTextLayout : NSObject
- (nonnull instancetype)initWithHocr:(nullable NSString *)hocr;
+ (nonnull instancetype)textLayoutWithHocr:(nullable NSString *)hocr;

/**
 * XML string containing information about text, style and layout of the image
 * that was processed.
 */
@property (nonatomic, readonly, nullable) NSString * hocr;

@end
