// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk-ocr.djinni

#pragma once

#include "geLogger.hpp"
#include <memory>

namespace ge {

class OCREngineProgressListener;
struct OCREngineConfiguration;
struct OCREngineInput;
struct OCREngineResult;

/** Recognizes text in an image */
class OCREngine {
public:
    virtual ~OCREngine() {}

    /**
     * Create an OCR engine
     * @param configuration An OCR engine configuration
     * @param progress_listener A listener that will receive updates about the OCR progress
     */
    static std::shared_ptr<OCREngine> create(const OCREngineConfiguration & configuration, const std::shared_ptr<::ge::Logger> & logger, const std::shared_ptr<OCREngineProgressListener> & progress_listener);

    /** Process the input image to extract text and layout information */
    virtual OCREngineResult recognizeText(const OCREngineInput & input) = 0;
};

}  // namespace ge
