// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk-ocr.djinni

#pragma once

#include <functional>

namespace ge {

/** The status of the OCR engine recognition */
enum class OCREngineError : int {
    SUCCESS,
    INTERNAL,
    FILENOTFOUND,
    INITIALIZATION,
};

}  // namespace ge

namespace std {

template <>
struct hash<::ge::OCREngineError> {
    size_t operator()(::ge::OCREngineError type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
