// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk-ocr.djinni

#pragma once

#include <string>
#include <utility>
#include <vector>

namespace ge {

/** The OCR engine configuration */
struct OCREngineConfiguration final {
    /**
     * Lists of language codes that should match the tessdata files
     * eg ["eng", "fra"] if both eng.trainedata and fra.trainedata are
     * present in the tessdata folder
     */
    std::vector<std::string> languages;
    /**
     * Absolute path to the tessdata folder containing the languages files
     * used for OCR
     */
    std::string tessdataPath;

    OCREngineConfiguration(std::vector<std::string> languages_,
                           std::string tessdataPath_)
    : languages(std::move(languages_))
    , tessdataPath(std::move(tessdataPath_))
    {}

    OCREngineConfiguration()
    : languages()
    , tessdataPath()
    {}
};

}  // namespace ge
