// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk-pdf.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, GSKPDFGeneratorError)
{
    GSKPDFGeneratorErrorSuccess,
    GSKPDFGeneratorErrorInternal,
    GSKPDFGeneratorErrorFileNotFound,
    GSKPDFGeneratorErrorInvalidPassword,
    GSKPDFGeneratorErrorInvalidPageSize,
    GSKPDFGeneratorErrorProcessorError,
    GSKPDFGeneratorErrorCodeInvalidInput,
};
