// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk-pdf.djinni

#import "GSKPDFSize.h"
#import "GSKTextLayout.h"
#import <Foundation/Foundation.h>

/** Describes a page of a PDF document for the PDF generator. */
@interface GSKPDFPage : NSObject
- (nonnull instancetype)initWithFilePath:(nonnull NSString *)filePath
                              inchesSize:(nonnull GSKPDFSize *)inchesSize
                              textLayout:(nullable GSKTextLayout *)textLayout;
+ (nonnull instancetype)PDFPageWithFilePath:(nonnull NSString *)filePath
                                 inchesSize:(nonnull GSKPDFSize *)inchesSize
                                 textLayout:(nullable GSKTextLayout *)textLayout;

/** Absolute path to an image file */
@property (nonatomic, readonly, nonnull) NSString * filePath;

@property (nonatomic, readonly, nonnull) GSKPDFSize * inchesSize;

/**
 * If provided, the text will be included in the resulting PDF at the specified positions
 * with an invisible font type. This text can then be searched and selected.
 */
@property (nonatomic, readonly, nullable) GSKTextLayout * textLayout;

@end
